# Generated by Django 5.0.6 on 2024-06-13 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('apellido', models.CharField(blank=True, max_length=25)),
                ('calle', models.CharField(blank=True, max_length=50)),
                ('nro', models.CharField(blank=True, max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('contacto', models.CharField(blank=True, max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
